### ISSUE TITLE
Question: How to save

### ISSUE THREAD

**Issue by rkrater** [sockeqwe/mosby-conductor#16]
_I'm new to Mosby, Conductor and  SQLBrite and looking at the sample app to understand everything..._

In `CreateTaskPresenter `the function `saveTask()` is empty. What is the best way to save the task to the database?

I see `dao: TaskDao` passed in and can call `dao.createTask()` but what's the correct way to access the task's data?

**Comment by sockeqwe** [comment]
The sample alp is a work in Progress.  There should be a taskDao.getTasks()
method to load the list of tasks.

Basically do the same as you would do with Model-View-Presenter  or
Model-View-Intent but except that a Conductor Controller is the View
instead of Activity or Fragment.

Rob Krater <notifications@github.com> schrieb am Mi., 8. Feb. 2017, 18:20:
