### ISSUE TITLE
README is incorrect in regard to a mosby-conductor mvp Presenter lifecycle

### ISSUE THREAD

**Issue by dimsuz** [sockeqwe/mosby-conductor#18]
It seems like README documentation about Presenter lifecycle is incorrect.

It states that

> Presenter will be destroyed in Controller.onDestroyView() except screen orientation changes

But `mosby-conductor` has [this bit of code](https://github.com/sockeqwe/mosby-conductor/blob/master/mvp/src/main/java/com/hannesdorfmann/mosby3/mvp/conductor/delegate/MvpConductorLifecycleListener.java#L67-L74)

```java
  @Override public void preDestroyView(@NonNull Controller controller, @NonNull View view) {
    P presenter = getCallback().getPresenter();
    if (presenter == null) {
      throw new NullPointerException(
          "Presenter returned from getPresenter() is null in " + callback);
    }
    presenter.detachView(controller.getActivity().isChangingConfigurations());
  }
```

And there's nothing here which would destroy presenter. Only `detachView()` is getting called, even in non orientation change scenario.

In fact `createPresenter()` is also called *only* if `getCallback()` (which is == `Controller`) returns null presenter, but it will be null only for new Controllers and Controllers won't be null until they are removed from backstack or destroyed...

```java
  @Override public void postCreateView(@NonNull Controller controller, @NonNull View view) {

    MvpConductorDelegateCallback<V, P> callback = getCallback();

    P presenter = callback.getPresenter();
    if (presenter == null) {
      presenter = callback.createPresenter();
      .......
    }
}
```

Or am I getting something wrong here?

**Comment by sockeqwe** [comment]
Yes, you are right, the docs are not very accurate.
A Presenter is actually never destroyed (only view detached as you have noticed correctly) ...
What I was trying to say is, the view will be detached permantently (calls `presenter.detachView(false)`  and then the presenter will be destroyed (because removed from backstack) and Garbage Collector collects Controller and corresponding Presenter.

>  but it will be null only for new Controllers and Controllers won't be null until they are removed from backstack or destroyed...

Yes, the idea is that one Presenter is created when the controller appears for the first time. For example, no Presenter will be created again when the user navigates back from backstack to the controller, because the Presenter is already there. Is that an issue in your opinion?

**Comment by dimsuz** [comment]
Ah, I see.

> Is that an issue in your opinion?

No, I think it is good, because I can rely on the same presenter will be used whenever I user in the same flow. This can be used to save some transitive state in the presenter for the situation when user goes forward and then returns back. Otherwise it will need to be saved elsewhere.

I even think that either way could be used, but it is important to clarify the behavior for library users, so perhaps it would be good to update README a bit. I guess the issue can be closed with whatever outcome you decide :)
