### ISSUE TITLE
Question: Status of the project & sample app

### ISSUE THREAD

**Issue by tmtron** [sockeqwe/mosby-conductor#9]
Is this project active at all? Is it still used by someone in production?

I'm asking, because I had a look at the sample app and I think there are some issues (unless I'm missing something):

- date picker crashed when clicking any date
- the [DateTimePickerController.submitDateTime()](https://github.com/sockeqwe/mosby-conductor/blob/master/app/src/main/java/com/hannesdorfmann/mosby/conductor/sample/create/datetimepicker/DateTimePickerController.kt#L114) is not implemented, so you can never leave the date-time picker, right?
- how could you leave the [CreateTaskController](https://github.com/sockeqwe/mosby-conductor/blob/master/app/src/main/java/com/hannesdorfmann/mosby/conductor/sample/create/CreateTaskController.kt)? Theres no OK button, or the like?

**Comment by sockeqwe** [comment]
Hi, 
yes this project is active but has been paused temporarily because I'm working on a next major release of Mosby (version 3.0). Once Mosby 3.0 is published, I will publish a first major version of this project (mosby-conductor) inclusive a full working sample.  At the moment the sample is not complete at all and there are major issues not cause by mosby nor by conductor. I simply haven't found time to finish the sample.

Regarding production ready: I doubt that there are many apps using conductor in production  yet and I doubt even more that there are apps using mosby-conductor in production yet. I have started building apps using conductor + mosby, but none of them has been published yet. Basically because I hadn't time to finish those  apps.

**Comment by tmtron** [comment]
thanks for the fast response - that explains a lot :)

Looking forward to MosbyV3

**Comment by dimsuz** [comment]
> I doubt that there are many apps using conductor in production and I doubt even more that there are apps using mosby-conductor in production. 

Pretty soon there will be at least one using both in production :)
